### ISSUE TITLE
Repository naming 일관성 있게 유지해주세요

### ISSUE THREAD

**Issue by jinhongjung** [alps-jbnu/23ALPStudy#2]
내용무입니다

**Comment by joonas-yoon** [comment]
같은 성격의 repo가 한 3개 있는거같은데, 이름 변경해도 한동안은 자동으로 redirect 될 거라 접속 못 하는 걱정은 덜 해도 될 듯 하네요.

이번 기회에 규칙을 정해서 일괄 변경하면 이쁘겠네요?

**Comment by AFpine** [comment]
기존 22ALPStudy 와 일관성을 유지하기 위해 23ALPStudy로 교체하겠습니다. 감사합니다.
